### ISSUE TITLE
Question - What is status of nutanix client?

### ISSUE THREAD

**Issue by spuder** [Tfindelkind/ntnx-golang-client-sdk#2]
We are new nutanix customers. We are looking at [developing a terraform plugin](https://github.com/hashicorp/terraform/issues/5923). Evaluating if it should leverage this client. 

Would like to know
- Plans to maintain this project? 
- How complete is the plugin?
- Any plans to adopt version 1.0 of the acropolis api?

**Comment by Tfindelkind** [comment]
Good morning. This client will be used in an actual project  (automation VM for Nutanix) I am an working on right now and it is under heavy development. It will only support a small subset of the whole API in the first release. I heared that there will be an official Nutanix API in the future. Let me ask internal if and when it is available. My plan is to maintain this project as long as there is no official release.

**Comment by spuder** [comment]
Great, When you say:

> there will be an official Nutanix API in the future. 

Do you mean that there will be an official go library?

**Comment by Tfindelkind** [comment]
correct

**Comment by Tfindelkind** [comment]
So the last version could be considered as a stable release. Remember it only represent a small subset of the v0.8 and v1 Nutanix API.
