### ISSUE TITLE
Consider rename project to acropolis-sdk-go ? 

### ISSUE THREAD

**Issue by spuder** [Tfindelkind/ntnx-golang-client-sdk#3]
We are going to start heavily depending on this library and make pull requests to add features. We plan on assigning a developer to add acropolis support to terraform and packer based on this library. 

Thoughts on renaming the library to better match nutanix & go naming conventions? 

https://github.com/aws/aws-sdk-go
https://github.com/google/google-api-go-client/
https://github.com/Azure/azure-sdk-for-go

Instead of `ntnx-golang-client-sdk`, could you rename it to `acropolis-sdk-go`?

**Comment by Tfindelkind** [comment]
For sure this can be done. This library should help to drive the adoption of the Nutanix REST API. I am glad you could leverage it. BUT in just a few weeks/month there should be an official golang library based on the new v3 Nutanix REST API. It might be that you may invest time and effort which may change a lot. I am using this library for my own projects which I need to redesign as well.

**Comment by spuder** [comment]
Where did you learn of the official library? I've asked people who work at nutanix and they say they don't know about this.

**Comment by Tfindelkind** [comment]
I am working for Nutanix and like all features for the future, this may be there in the next release or not. But http://myvirtualcloud.net/?p=8078 talks about a self service portal and for this something new is needed or? I know more but not allowed to discuss all pubic.

**Comment by Tfindelkind** [comment]
done

**Comment by spuder** [comment]
We will actually not use this library and instead wait for the official library and the new api
